export enum ActionType {
  ADD_CHECK = "ADD_CHECK",
  CHANGE_PROFILE = "CHANGE_PROFILE",
  ADD_PARTIAL_PROFILE = "ADD_PARTIAL_PROFILE",
  ADD_ROLE = "ADD_ROLE",
  ADD_ORDERS_ADVERTISER = "ADD_ORDERS_ADVERTISER",
  ADD_ORDER = "ADD_ORDER",
}
