export enum ActionType {
  ADD_CHECK = "ADD_CHECK",
  CHANGE_PROFILE = "CHANGE_PROFILE",
  ADD_PARTIAL_PROFILE = "ADD_PARTIAL_PROFILE",
  ADD_ROLE = "ADD_ROLE",
  ADD_ORDERS = "ADD_ORDERS_ADVERTISER",
  ADD_ORDER = "ADD_ORDER",
  ADD_MEDIA_PERSONS = "ADD_MEDIA_PERSONS",
  DELETE_ORDERS = "DELETE_ORDERS",
  ADD_NAME_ORDER_URL = "ADD_NAME_ORDER_URL",
  ADD_SELECTED_PROFILE = "ADD_SELECTED_PROFILE",
  ADD_CHATS = "ADD_CHATS",
}
